"""Internal allowlist for the subset of MetaTrader5 used by M1."""

from typing import Protocol

from ai_trading_team.schemas.enums import Timeframe


class MT5ReadBackend(Protocol):
    """Dependency-injection boundary containing read-only calls and lifecycle methods."""

    @property
    def package_version(self) -> str: ...

    def initialize(self, path: str | None, timeout_ms: int, portable: bool) -> bool: ...

    def login(self, login: int, password: str, server: str, timeout_ms: int) -> bool: ...

    def shutdown(self) -> None: ...

    def last_error(self) -> tuple[int | None, str]: ...

    def version(self) -> object | None: ...

    def terminal_info(self) -> object | None: ...

    def account_info(self) -> object | None: ...

    def symbols_get(self, pattern: str | None) -> object | None: ...

    def symbol_info(self, symbol: str) -> object | None: ...

    def symbol_info_tick(self, symbol: str) -> object | None: ...

    def copy_rates_from_pos(
        self,
        symbol: str,
        timeframe: Timeframe,
        start_position: int,
        count: int,
    ) -> object | None: ...

    def positions_get(self, symbol: str | None) -> object | None: ...
